- Update Curl to version number 7.5.13 - Remove some patches - Rewrite "get_ssl_handle" patch

diff --git a/libs/curl/buildconf b/libs/curl/buildconf
--- a/libs/curl/buildconf
+++ b/libs/curl/buildconf
@@ -1,4 +1,26 @@
 #!/bin/sh
+#***************************************************************************
+#                                  _   _ ____  _
+#  Project                     ___| | | |  _ \| |
+#                             / __| | | | |_) | |
+#                            | (__| |_| |  _ <| |___
+#                             \___|\___/|_| \_\_____|
+#
+# Copyright (C) 1998 - 2005, Daniel Stenberg, <daniel@haxx.se>, et al.
+#
+# This software is licensed as described in the file COPYING, which
+# you should have received as part of this distribution. The terms
+# are also available at http://curl.haxx.se/docs/copyright.html.
+#
+# You may opt to use, copy, modify, merge, publish, distribute and/or sell
+# copies of the Software, and permit persons to whom the Software is
+# furnished to do so, under the terms of the COPYING file.
+#
+# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
+# KIND, either express or implied.
+#
+# $Id: buildconf,v 1.45 2006/01/06 22:08:39 bagder Exp $
+###########################################################################
 
 die(){
 	echo "$@"
@@ -13,6 +35,7 @@ findtool(){
   IFS=":"
   for path in $PATH
   do
+    # echo "checks for $file in $path" >&2
     if test -f "$path/$file"; then
       echo "$path/$file"
       return
@@ -85,8 +108,7 @@ fi
 
 echo "buildconf: automake version $am_version (ok)"
 
-ac=`findtool aclocal`
-
+ac=`findtool ${ACLOCAL:-aclocal}`
 if test -z "$ac"; then
   echo "buildconf: aclocal not found. Weird automake installation!"
   exit 1
@@ -107,11 +129,16 @@ LIBTOOL_WANTED_VERSION=1.4.2
 # glibtool, with 'libtool' being something completely different.
 libtool=`findtool glibtool 2>/dev/null`
 if test ! -x "$libtool"; then
-  libtool=`findtool libtool`
+  libtool=`findtool ${LIBTOOL:-libtool}`
 fi
 
-# set the LIBTOOLIZE here so that glibtoolize is used if glibtool was found
-LIBTOOLIZE="${libtool}ize"
+if test -z "$LIBTOOLIZE"; then
+  # set the LIBTOOLIZE here so that glibtoolize is used if glibtool was found
+  # $libtool is already the full path
+  libtoolize="${libtool}ize"
+else
+  libtoolize=`findtool $LIBTOOLIZE`
+fi
 
 lt_pversion=`$libtool --version 2>/dev/null|head -n 1|sed -e 's/^[^0-9]*//g' -e 's/[- ].*//'`
 if test -z "$lt_pversion"; then
@@ -150,7 +177,7 @@ fi
 
 echo "buildconf: libtool version $lt_version (ok)"
 
-if test -f "$LIBTOOLIZE"; then
+if test -f "$libtoolize"; then
   echo "buildconf: libtoolize found"
 else
   echo "buildconf: libtoolize not found. Weird libtool installation!"
@@ -173,14 +200,14 @@ fi
 #--------------------------------------------------------------------------
 # perl check
 #
-PERL=`findtool perl`
+PERL=`findtool ${PERL:-perl}`
 
 # ------------------------------------------------------------
 
 # run the correct scripts now
 
 echo "buildconf: running libtoolize"
-${LIBTOOLIZE:-libtoolize} --copy --automake --force || die "The libtool command failed"
+$libtoolize --copy --automake --force || die "The libtoolize command failed"
 echo "buildconf: running aclocal"
 ${ACLOCAL:-aclocal} $ACLOCAL_FLAGS || die "The aclocal command line failed"
 if test -n "$PERL"; then
@@ -199,12 +226,8 @@ ${AUTOCONF:-autoconf}     || die "The autoconf command failed"
 
 if test -d ares; then
   cd ares
-  echo "buildconf: running ares/libtoolize"
-${LIBTOOLIZE:-libtoolize} --copy --automake --force || die "The libtool command failed"
-  echo "buildconf: running ares/aclocal"
-  ${ACLOCAL:-aclocal} $ACLOCAL_FLAGS || die "The ares aclocal command failed"
-  echo "buildconf: running ares/autoconf"
-  ${AUTOCONF:-autoconf}     || die "The ares autoconf command failed"
+  echo "buildconf: running in ares"
+  ./buildconf
   cd ..
 fi
 
